In [44]:
import pandas as pd


data = {
    'Product': ['A', 'B', 'C', 'A', 'B', 'C'],
    'Region': ['North', 'North', 'North', 'South', 'South', 'South'],
    'Sales': [100, 200, 150, 300, 400, 350]
}

df = pd.DataFrame(data)
print(df)


pivot_df = df.pivot(index='Region', columns='Product', values='Sales')

print(pivot_df)

  Product Region  Sales
0       A  North    100
1       B  North    200
2       C  North    150
3       A  South    300
4       B  South    400
5       C  South    350
Product    A    B    C
Region
North    100  200  150
South    300  400  350

In [45]:

data = {
    'Product': ['A', 'B', 'C', 'A', 'B', 'C', 'A', 'B', 'C'],
    'Region': ['North', 'North', 'North', 'South', 'South', 'South', 'East', 'East', 'East'],
    'Sales': [100, 200, 150, 300, 400, 350, 500, 600, 550]
}

df = pd.DataFrame(data)
print(df)


pivot_table_df = df.pivot_table(values='Sales', index='Region', columns='Product', aggfunc='sum', fill_value=0)

print(pivot_table_df)

  Product Region  Sales
0       A  North    100
1       B  North    200
2       C  North    150
3       A  South    300
4       B  South    400
5       C  South    350
6       A   East    500
7       B   East    600
8       C   East    550
Product    A    B    C
Region
East     500  600  550
North    100  200  150
South    300  400  350

In [46]:

data = {
    'Product': ['A', 'B', 'C', 'A', 'B', 'C', 'A', 'B', 'C'],
    'Region': ['North', 'North', 'North', 'South', 'South', 'South', 'East', 'East', 'East'],
    'Sales': [100, 200, 150, 300, 400, 350, 500, 600, 550],
    'Profit': [10, 20, 15, 30, 40, 35, 50, 60, 55]
}

df = pd.DataFrame(data)
print(df)

pivot_table_df = df.pivot_table(values=['Sales', 'Profit'], index='Region', columns='Product', aggfunc={'Sales': 'sum', 'Profit': 'mean'}, fill_value=0)

print(pivot_table_df)

  Product Region  Sales  Profit
0       A  North    100      10
1       B  North    200      20
2       C  North    150      15
3       A  South    300      30
4       B  South    400      40
5       C  South    350      35
6       A   East    500      50
7       B   East    600      60
8       C   East    550      55
        Profit             Sales
Product      A     B     C     A    B    C
Region
East      50.0  60.0  55.0   500  600  550
North     10.0  20.0  15.0   100  200  150
South     30.0  40.0  35.0   300  400  350

In [47]:
import pandas as pd

data=pd.read_csv('Walmart_Sales.csv')
data

,Store,Date,Weekly_Sales,Holiday_Flag,Temperature,Fuel_Price,CPI,Unemployment
0,1,05-02-2010,1643690.90,0,42.31,2.572,211.096358,8.106
1,1,12-02-2010,1641957.44,1,38.51,2.548,211.242170,8.106
2,1,19-02-2010,1611968.17,0,39.93,2.514,211.289143,8.106
3,1,26-02-2010,1409727.59,0,46.63,2.561,211.319643,8.106
4,1,05-03-2010,1554806.68,0,46.50,2.625,211.350143,8.106
...,...,...,...,...,...,...,...,...
6430,45,28-09-2012,713173.95,0,64.88,3.997,192.013558,8.684
6431,45,05-10-2012,733455.07,0,64.89,3.985,192.170412,8.667
6432,45,12-10-2012,734464.36,0,54.47,4.000,192.327265,8.667
6433,45,19-10-2012,718125.53,0,56.47,3.969,192.330854,8.667
6434,45,26-10-2012,760281.43,0,58.85,3.882,192.308899,8.667

In [48]:
pivot_df = data.pivot(index='Store', columns='Date', values='Weekly_Sales')

print(pivot_df)

Date   01-04-2011  01-06-2012  01-07-2011  01-10-2010  02-03-2012  02-04-2010  \
Store
1      1495064.75  1624477.58  1488538.09  1453329.50  1688420.76  1594968.28
2      1800171.36  1910092.37  1866243.00  1827440.43  1952555.66  2066187.72
3       374556.08   432268.53   368962.72   358784.10   469752.56   423294.40
4      1900246.47  2179360.94  2051533.53  1842821.02  2206319.90  1979247.12
5       314316.55   359867.80   327093.89   283178.12   359206.21   331406.00
6      1459276.77  1681121.38  1694551.15  1328468.89  1550385.65  1770333.90
7       513409.67   598495.02   704344.21   448998.73   551058.13   561145.14
8       878762.30   921161.20   883683.35   804105.49   952264.91   914500.91
9       520962.14   583648.59   537064.03   495692.19   619498.28   545206.32
10     1827733.18  1767471.48  1751369.75  1645892.97  1990371.02  2138651.97
11     1258674.12  1361595.33  1297472.06  1182490.46  1438383.44  1446210.26
12     1005463.49   981345.20   961993.34   850936.26  1147636.96  1011822.30
13     1864238.64  2035431.39  2048035.74  1765584.48  1969742.76  2142482.14
14     1869110.55  2049485.49  2074668.19  1855703.66  1926004.99  2495630.51
15      542556.05   663971.26   674669.16   566945.95   541292.64   718470.71
16      459756.11   532311.93   608737.56   463977.54   464189.09   490503.69
17      795859.23   938914.28   940554.34   829207.27   856178.47   848521.17
18      938083.17  1118313.70  1087051.26   948977.50  1047178.91  1254107.84
19     1305950.22  1450733.29  1462731.93  1379456.30  1308977.05  1642970.27
20     1927993.09  2143126.59  2053165.41  1933719.21  2148822.76  2405395.22
21      732056.37   695439.83   784639.12   677158.39   764385.40   753664.12
22      951588.37  1102857.37  1077491.68   905987.17   974866.65  1177340.99
23     1182694.95  1476144.34  1492507.44  1129909.44  1322852.20  1556627.62
24     1163803.30  1467722.19  1445596.61  1215273.20  1213994.39  1478321.26
25      618377.79   694765.95   706206.86   658640.14   643155.89   822486.37
26      849231.61  1015853.03  1070119.09   923221.52   955641.74  1029849.20
27     1628868.28  1900638.60  1949983.93  1543532.83  1509323.09  2053952.97
28     1336838.41  1245480.95  1319054.57  1203080.41  1451740.57  1441559.40
29      475615.26   576252.35   567114.60   474698.01   500801.72   599629.25
30      437926.79   427021.18   428782.38   445475.30   438640.61   457884.06
31     1344890.73  1404516.29  1371889.27  1213981.64  1427881.22  1357600.68
32     1051121.02  1157557.79  1199845.29  1061089.56  1153332.89  1131732.94
33      232769.09   261131.09   226702.36   224294.39   248051.53   274634.52
34      884233.67   977062.44   911106.22   865709.11   990263.70   979428.66
35      762620.94   932195.52   874453.88   771065.21   766571.10  1189556.47
36      385672.11   306005.53   354270.77   422169.47   315396.72   435972.82
37      534578.78   531811.85   517021.30   529877.93   525559.17   540189.70
38      382098.13   435579.70   387334.04   360256.58   471115.38   368929.55
39     1316849.36  1640476.77  1429829.36  1219583.91  1453047.02  1463942.62
40      841889.08  1037464.27  1048866.30   891152.33   927732.02  1041202.13
41     1179125.48  1374891.36  1333347.78  1109216.35  1239813.26  1168826.39
42      508432.17   521953.78   506343.83   481523.93   585895.34   505907.41
43      611585.54   605078.62   586781.78   657108.77   693249.98   650102.80
44      281514.26   323410.94   315273.08   300152.45   316687.22   286197.50
45      712425.76   837144.63   791495.25   690007.76   782796.01   877235.96

Date   02-07-2010  02-09-2011  02-12-2011  03-02-2012  ...  29-06-2012  \
Store                                                  ...
1      1492418.14  1550229.22  1584083.95  1636339.65  ...  1540421.49
2      2003940.64  1809119.70  1954952.00  1935299.94  ...  1881046.12
3       381151.72   375988.69   472511.32   424960.66  ...   422965.33
4      1881337.21  2078420.31  2180999.26  2173373.91  ...  2128362.92
5       305993.27   315645.53   376225.61   333948.00  ...   329658.10
6      1759777.25  1481618.74  1688531.34  1496305.78  ...  1648863.46
7       575570.77   592355.24   591907.88   580453.32  ...   704335.41
8       852333.75   891387.14   986601.46   927610.69  ...   878298.22
9       528832.54   544643.33   613115.21   549967.89  ...   544770.70
10     1845893.87  1758587.35  2068097.18  1867403.01  ...  1707481.90
11     1302600.14  1297792.41  1399322.44  1376732.18  ...  1297028.60
12      951957.31  1052051.45  1071383.10  1058767.95  ...   943124.74
13     2018314.71  1953628.82  2051315.66  1927780.74  ...  2037663.71
14     2334788.42  1750891.47  2143080.57  1877410.36  ...  1591835.02
15      709337.11   649159.68   699028.66   523831.64  ...   624099.48
16      610641.42   580805.33   530492.84   475905.10  ...   570162.28
17      958875.37   847380.07   945267.68   864852.85  ...   982322.24
18     1257928.35   540922.94  1188047.61  1049772.04  ...  1097006.30
19     1549018.68  1609951.02  1484708.38  1345311.65  ...  1379652.65
20     2143676.77  2141765.98  2298776.83  2203523.20  ...  2055952.61
21      711470.80   705557.80   793184.25   680725.43  ...   716341.39
22     1120259.71   912762.76  1167621.14   958487.75  ...  1053881.78
23     1549113.18  1464295.69  1552886.59  1261872.67  ...  1451782.16
24     1563387.94  1196105.44  1335647.10  1249696.97  ...  1428869.90
25      759407.87   699779.00   878314.57   642776.40  ...   718890.81
26     1078455.48  1040143.14  1012498.49   939158.25  ...  1051190.44
27     2024554.10  1511717.53  1806924.74  1564246.02  ...  1842555.32
28     1399960.15  1468871.49  1368130.35  1531599.44  ...  1129031.98
29      581473.55   497085.91   579874.22   493159.35  ...   555954.13
30      450337.47   369722.32   412385.75   434080.74  ...   423192.40
31     1311704.92  1385769.03  1388809.43  1391479.91  ...  1349202.25
32     1187988.64  1152117.50  1179773.88  1156826.31  ...  1178211.81
33      267495.76   239198.36   220060.35   256091.32  ...   244338.31
34      919229.36   926455.64   988742.08   939367.14  ...   942970.63
35     1245827.08   813486.55   903606.03   746901.03  ...   892133.41
36      434252.15   350276.29   293350.51   310982.87  ...   291530.43
37      498292.53   530367.83   527117.81   555424.24  ...   508309.81
38      361181.48   416953.51   411252.02   457711.68  ...   404634.36
39     1352547.70  1465089.85  1632894.58  1396150.15  ...  1492388.98
40     1087578.78   957298.26  1059676.62   979552.34  ...   988764.84
41     1273279.79  1283849.38  1292436.23  1208825.60  ...  1355600.01
42      507168.80   537124.76   511883.36   588448.21  ...   507403.77
43      667353.79   594224.90   585028.26   629176.71  ...   593128.13
44      300628.19   309543.52   284309.34   325986.05  ...   338386.08
45      800147.84   726482.39   875699.81   757330.95  ...   773367.71

Date   29-07-2011  29-10-2010  30-03-2012  30-04-2010  30-07-2010  30-09-2011  \
Store
1      1352219.79  1384209.22  1649604.63  1425100.71  1371986.60  1394561.83
2      1680693.06  1802755.11  1857480.84  1802450.29  1804246.16  1650394.44
3       345381.29   348591.74   407488.84   361248.39   347955.05   368477.93
4      1989674.07  1933333.00  2089381.77  1817273.28  1796637.61  1929486.63
5       275142.17   278031.81   331318.73   298697.84   268929.03   292315.38
6      1483991.05  1385323.70  1508933.26  1498080.16  1532308.78  1307551.92
7       653382.62   465493.15   583322.20   373655.61   603547.16   488880.26
8       807082.19   830756.76   905935.29   778672.64   787295.09   809049.37
9       471449.98   508801.61   574985.37   491723.42   468675.19   508567.04
10     1745841.33  1741308.56  1815760.42  1790694.59  1832664.03  1627707.31
11     1212938.67  1195036.00  1300104.03  1239766.89  1250178.89  1190515.83
12      890547.07   955294.70  1025382.22   954220.22   913548.25   866401.45
13     1880785.69  1887895.07  1948982.70  1785823.37  1817887.23  1835662.69
14     1871021.01  1984768.34  1905033.01  2082355.12  2054843.28  1809989.29
15      577511.02   598301.50   557547.25   570791.11   619224.06   521297.31
16      582381.95   495022.51   485095.41   383550.93   562633.67   450075.31
17      861894.77   861941.25   872469.03   807798.73   833517.19   868191.05
18      954148.64  1038576.54  1009121.20  1060446.16  1078557.62   847348.08
19     1298775.80  1404576.48  1327139.35  1405065.57  1366395.96  1330757.22
20     1858440.92  1891816.00  2074721.74  1919053.21  1955896.59  1945808.26
21      751167.12   731756.65   724798.76   680532.69   715876.27   651970.48
22      944958.69  1025766.27   965769.93   977683.06   970773.64   953314.16
23     1319767.55  1112871.23  1261964.96  1259414.52  1319773.55  1275597.85
24     1310973.06  1244925.94  1230106.13  1259877.19  1387517.63  1246242.61
25      668390.82   674458.03   684348.92   706924.02   682124.34   639160.24
26     1005360.50   895069.88   922018.43   904503.85  1005324.28   959339.51
27     1744879.06  1688955.49  1615494.14  1805885.04  1816489.53  1599626.26
28     1114530.29  1231688.48  1209524.11  1186971.02  1150204.71  1120731.76
29      474653.06   527058.59   504566.28   501013.47   509872.77   446516.26
30      414245.96   438334.39   449603.91   456140.34   437893.76   387001.13
31     1308122.15  1257921.28  1318854.22  1243200.24  1231993.14  1285534.74
32     1169988.62  1115138.51  1108686.87  1066792.63  1065350.56  1088943.98
33      224806.96   213538.32   251327.67   275883.23   242047.03   229731.98
34      851461.90   926294.02   938861.77   859922.19   875976.83   871847.85
35      770820.27   857797.33   744525.69  1096930.65  1139131.78   749676.95
36      354361.08   392654.26   304144.90   457899.64   432451.91   314910.37
37      504974.95   514485.90   533734.94   517850.83   487912.95   516402.10
38      355131.33   341219.63   408679.36   337979.65   336378.38   366819.84
39     1426418.53  1294769.08  1499727.02  1263836.59  1308222.24  1311775.83
40      929096.90   875038.84   871945.64   816838.31   953393.02   912857.10
41     1248330.10  1144854.56  1239423.19  1063960.11  1211136.63  1160619.61
42      479256.80   476967.65   544408.14   477615.87   469598.57   510243.79
43      533917.52   610076.32   623258.40   630740.11   622112.23   555183.72
44      279677.00   286497.49   310027.29   272997.65   275020.96   299757.75
45      704680.97   732859.76   777254.06   737265.57   716859.27   698986.34

Date   30-12-2011  31-08-2012  31-12-2010
Store
1      1497462.72  1582083.40  1367320.01
2      1874226.52  1947083.30  1750434.55
3       410553.88   408838.73   382677.76
4      2007105.86  2081181.35  1794868.74
5       349624.88   344642.01   298180.18
6      1598080.52  1577439.81  1464050.02
7       815915.52   586467.16   729572.08
8       858572.22   976137.73   773586.49
9       549788.36   576879.15   459770.85
10     1930690.37  1650285.54  1707298.14
11     1352084.21  1372872.35  1172003.10
12     1111638.07  1061943.49   891736.91
13     1969056.91  2073855.42  1675292.00
14     1914148.89  1613342.19  1623716.46
15      603460.79   610185.32   543754.17
16      665861.06   551837.31   575317.38
17      777207.30   865924.20   635862.55
18     1010562.49  1117097.23   887907.01
19     1405168.06  1542719.87  1275146.94
20     2043245.00  2062481.56  1799737.79
21      804362.36   763867.59   672903.23
22      982661.14  1022270.86   774262.28
23     1213486.95  1577468.78  1169773.85
24     1363973.16  1344558.92  1208600.05
25      683665.37   714828.73   623092.54
26      972834.42  1053495.51   877268.29
27     1650604.60  1731935.43  1440963.00
28     1270036.53  1227118.75  1090558.57
29      551743.05   545844.91   465992.02
30      376777.45   439132.50   397631.02
31     1355405.95  1373651.49  1198071.60
32     1102367.65  1183979.27   955463.84
33      215359.21   237129.81   219804.85
34      965512.36   933487.71   902109.69
35      904650.55   931278.97   576332.05
36      287425.22   282647.48   359310.65
37      451327.61   538344.10   460331.70
38      342667.35   424904.95   303908.81
39     1537139.56  1710923.94  1230012.16
40      908853.15   987264.67   811318.30
41     1264014.16  1360517.52  1001790.16
42      454412.28   504760.57   428953.60
43      505405.85   593141.29   534740.30
44      263917.85   339490.69   241937.11
45      869403.63   734297.87   679156.20

[45 rows x 143 columns]